[project]
name = "hw3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "atproto>=0.0.59",
    "doublemetaphone>=1.1",
    "perception>=0.7.7",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "scipy>=1.15.2",
]
